version: "3.3"

services:
  server:
    build: .
    container_name: demo/paragon-web-shop:latest
    depends_on:
      - database
    ports:
      - 3000:3000
    links:
      - database
    command: npm run start-docker
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=paragon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local